

shell /usr/bin/fish


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
font_size 17.0
#NNEVER REMIND ME
confirm_os_window_close 0
#cursor_trail
cursor_trail 100
cursor_trail_decay 0.0 0.3
cursor_trail_start_threshold 10
