cursor            #e6b6f1
cursor_text_color #452152

foreground            #eae0e7
background            #110d12
selection_foreground  #3a2c3d
selection_background  #d5c0d7
url_color             #d5c0d7

#: black 000000 767676
color0  #161217
color8  #383339
#: red cc0403 f2201f
color1  #8c794b
color9  #cec1a2
#: green 19cb00 23fd00
color2  #d5c0d7
color10 #f2dcf3
#: yellow cecb00 fffd00
color3  #f5b7b3
color11 #ffdad7
#: blue 0d73cc 1a8fff
color4  #5e386a
color12 #e6b6f1
#: magenta cb1ed1 fd28ff
color5  #514254
color13 #d5c0d7
#: cyan 0dcdcd 14ffff
color6  #663b38
color14 #f5b7b3
#: white dddddd ffffff
color7  #cfc3cd
color15 #eae0e7

mark1_foreground #2e0a3b
mark1_background #f9d8ff
mark2_foreground #241727
mark2_background #f2dcf3
mark3_foreground #331110
mark3_background #ffdad7

active_tab_foreground #452152
active_tab_background #e6b6f1
inactive_tab_foreground #f9d8ff
inactive_tab_background #5e386a

active_border_color #e6b6f1
inactive_border_color #452152
# bell_border_color #ff5a00
